# Generated by Django 5.0.3 on 2024-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
