# Generated by Django 5.0.3 on 2024-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_postjob_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='slug',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
