# Generated by Django 5.0.3 on 2024-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_jobapplicant_city_jobapplicant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='zip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
