# Generated by Django 5.0.3 on 2024-05-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0008_withdrawnapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawnapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Employer.jobapplicant'),
        ),
    ]
