# Generated by Django 5.0.3 on 2024-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0010_jobapplicant_is_withdrawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
