# Generated by Django 5.0.3 on 2024-05-27 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_jobapplicant_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
