# Generated by Django 5.0.3 on 2024-05-27 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0012_postjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
