# Generated by Django 5.0.3 on 2024-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0014_remove_jobapplicant_is_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='resume',
            field=models.FileField(upload_to='Resume/'),
        ),
    ]
