# Generated by Django 5.0.3 on 2024-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0015_alter_jobapplicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='resume',
            field=models.FileField(upload_to='Resume'),
        ),
    ]
