# Generated by Django 5.0.3 on 2024-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0016_jobapplicant_is_withdrawn_alter_jobapplicant_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='is_withdrawn',
        ),
        migrations.AlterField(
            model_name='postjob',
            name='Employment_Type',
            field=models.CharField(choices=[('Internship', 'InterShip'), ('Partime', 'PartTime'), ('Fulltime', 'FullTime')], max_length=20),
        ),
    ]
