# Generated by Django 5.0.3 on 2024-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0017_remove_jobapplicant_is_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='Employment_Type',
            field=models.CharField(choices=[('Internship', 'InterShip'), ('PartTime', 'PartTime'), ('Fulltime', 'FullTime')], max_length=20),
        ),
    ]
