# Generated by Django 5.0.3 on 2024-07-09 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0018_alter_postjob_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 9, 7, 49, 47, 844805, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
