# Generated by Django 5.0.3 on 2024-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0020_remove_postjob_date_alter_postjob_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
