# Generated by Django 5.0.3 on 2024-07-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0021_alter_postjob_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('s', 'shortlist'), ('u', 'underProcess'), ('r', 'rejected')], max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.jobapplicant')),
            ],
        ),
    ]
