# Generated by Django 5.0.3 on 2024-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0022_statusofapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofapplication',
            name='status',
            field=models.CharField(choices=[('s', 'shortlist'), ('u', 'underProcess'), ('r', 'rejected'), ('p', 'pending')], max_length=20),
        ),
    ]
