# Generated by Django 5.0.3 on 2024-07-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0024_statusofapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusofapplication',
            name='user',
        ),
    ]
