# Generated by Django 5.0.3 on 2024-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
